import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  convertInchesToTwip,
} from 'docx';

function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const regex = /\*\*([^*]+)\*\*|\*([^*]+)\*/g;
  let last = 0;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text)) !== null) {
    if (match.index > last) {
      runs.push(new TextRun({ text: text.slice(last, match.index) }));
    }
    if (match[1] !== undefined) {
      runs.push(new TextRun({ text: match[1], bold: true }));
    } else if (match[2] !== undefined) {
      runs.push(new TextRun({ text: match[2], italics: true, color: '64748B' }));
    }
    last = match.index + match[0].length;
  }

  if (last < text.length) {
    runs.push(new TextRun({ text: text.slice(last) }));
  }

  return runs.length ? runs : [new TextRun({ text })];
}

export async function buildDocx(content: string, coupleName: string, weddingDate: string): Promise<Buffer> {
  const lines = content.split('\n');
  const children: Paragraph[] = [];

  // Header
  children.push(
    new Paragraph({
      children: [new TextRun({ text: coupleName, bold: true, size: 36, font: 'Georgia', color: '1E293B' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 },
    }),
    new Paragraph({
      children: [new TextRun({ text: weddingDate, size: 22, color: '64748B' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  );

  for (const line of lines) {
    if (!line.trim()) {
      children.push(new Paragraph({ children: [new TextRun({ text: '' })], spacing: { after: 80 } }));
      continue;
    }

    if (/^# /.test(line)) {
      children.push(new Paragraph({
        children: [new TextRun({ text: line.slice(2), bold: true, size: 32, font: 'Georgia', color: '1E293B' })],
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 360, after: 160 },
      }));
      continue;
    }

    if (/^## /.test(line)) {
      children.push(new Paragraph({
        children: [new TextRun({ text: line.slice(3).toUpperCase(), bold: true, size: 22, color: 'C9A84C', font: 'Georgia' })],
        spacing: { before: 320, after: 120 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: 'C9A84C', space: 4 } },
      }));
      continue;
    }

    if (/^### /.test(line)) {
      children.push(new Paragraph({
        children: [new TextRun({ text: line.slice(4), bold: true, size: 24, font: 'Georgia', color: '334155' })],
        spacing: { before: 240, after: 80 },
      }));
      continue;
    }

    if (/^---/.test(line)) {
      children.push(new Paragraph({
        children: [new TextRun({ text: '' })],
        border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0', space: 4 } },
        spacing: { before: 160, after: 160 },
      }));
      continue;
    }

    if (/^  - /.test(line)) {
      children.push(new Paragraph({
        children: parseInline(line.slice(4)),
        indent: { left: convertInchesToTwip(0.75) },
        spacing: { after: 40 },
        bullet: { level: 1 },
      }));
      continue;
    }

    if (/^- /.test(line)) {
      const stripped = line.slice(2);
      children.push(new Paragraph({
        children: parseInline(stripped),
        indent: { left: convertInchesToTwip(0.375) },
        spacing: { after: 60 },
        bullet: { level: 0 },
      }));
      continue;
    }

    children.push(new Paragraph({
      children: parseInline(line),
      spacing: { after: 80 },
    }));
  }

  // Footer credit
  children.push(
    new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 480 } }),
    new Paragraph({
      children: [new TextRun({ text: 'Generated by Sundial', size: 18, color: 'CBD5E1', italics: true })],
      alignment: AlignmentType.CENTER,
    }),
  );

  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(1),
            bottom: convertInchesToTwip(1),
            left: convertInchesToTwip(1.25),
            right: convertInchesToTwip(1.25),
          },
        },
      },
      children,
    }],
  });

  return Packer.toBuffer(doc);
}
